### PR TITLE
Glibc 2.33 fix.

### LINKED ISSUE #167: Build fails with glibc 2.33
Using the just released glibc I see the following error:

```
[   39s] libsystem.c:333:1: error: no previous prototype for '__xstat' [-Werror=missing-prototypes]
[   39s]   333 | __xstat (int version, const char *path, struct stat *buf)
[   39s]       | ^~~~~~~
[   39s] libsystem.c:342:1: error: no previous prototype for '__xstat64' [-Werror=missing-prototypes]
[   39s]   342 | __xstat64 (int version, const char *path, struct stat64 *buf)
[   39s]       | ^~~~~~~~~
[   39s] libsystem.c:351:1: error: no previous prototype for '__fxstatat' [-Werror=missing-prototypes]
[   39s]   351 | __fxstatat(int ver, int dirfd, const char *pathname, struct stat *buf, int flags)
[   39s]       | ^~~~~~~~~~
[   39s] libsystem.c:360:1: error: no previous prototype for '__fxstatat64' [-Werror=missing-prototypes]
[   39s]   360 | __fxstatat64(int ver, int dirfd, const char *pathname, struct stat64 *buf, int flags)
[   39s]       | ^~~~~~~~~~~~
```

It's related to fact that glibc stopped declaring the function. So the `dlsym` call may fail as well.

### PR DESCRIPTION
**Pull request by marxin**
The library does not declare __fxstatat64 and friends in a header file.
Thus the following warning appears:

```
libsystem.c:333:1: error: no previous prototype for '__xstat' [-Werror=missing-prototypes]
  333 | __xstat (int version, const char *path, struct stat *buf)
      | ^~~~~~~
libsystem.c:342:1: error: no previous prototype for '__xstat64' [-Werror=missing-prototypes]
  342 | __xstat64 (int version, const char *path, struct stat64 *buf)
      | ^~~~~~~~~
libsystem.c:351:1: error: no previous prototype for '__fxstatat' [-Werror=missing-prototypes]
  351 | __fxstatat(int ver, int dirfd, const char *pathname, struct stat *buf, int flags)
      | ^~~~~~~~~~
libsystem.c:360:1: error: no previous prototype for '__fxstatat64' [-Werror=missing-prototypes]
  360 | __fxstatat64(int ver, int dirfd, const char *pathname, struct stat64 *buf, int flags)
      | ^~~~~~~~~~~~
```

Fixed #167.

### CODE REVIEW

File: tests/src/libsystem.c [hunk 1]
```diff
@@ -329,6 +329,10 @@ stat64 (const char *path, struct stat64 *buf)
     return _stat64 (new_path, buf);
 }
 
+// glibc 2.36 and newer does not declare these functions in a header file
```
Comment (ggardet) [inline tests/src/libsystem.c:332]: `s/2.36/2.33/`?

Comment (marxin) [reply tests/src/libsystem.c]: Yep, fixed.

**Comment by robert-ancell** [comment]
Thanks @marxin!
